/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package svacee.view;

import java.awt.Color;
import svacee.controller.LerCSV;

/**
 *
 * @author Bianca, João Daniel e Vinícius
 */
public class SvaceeMainForm extends javax.swing.JFrame {

    LerCSV lcsv;

    /**
     * Creates new form SvaceeMainForm
     */
    public SvaceeMainForm() {
        initComponents();
        getContentPane().setBackground(Color.white);

        bDado.setToolTipText("Obter dados a partir de arquivos CSV");
        bGrafico.setToolTipText("Obter dados a partir do gráfico");
        bTabela.setToolTipText("Obter dados a partir da tabela");
        bSobre.setToolTipText("Obter informações sobre o software");
        bSair.setToolTipText("Sair");

        lcsv = new LerCSV();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        barraFerramenta = new javax.swing.JToolBar();
        bDado = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        bTabela = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        bGrafico = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        bSobre = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        bSair = new javax.swing.JButton();
        menu = new javax.swing.JMenuBar();
        mArquivo = new javax.swing.JMenu();
        smDado = new javax.swing.JMenuItem();
        smSair = new javax.swing.JMenuItem();
        mVisualizar = new javax.swing.JMenu();
        smTabela = new javax.swing.JMenuItem();
        smGrafico = new javax.swing.JMenuItem();
        mAjuda = new javax.swing.JMenu();
        smSobre = new javax.swing.JMenuItem();

        jPanel1.setLayout(new java.awt.BorderLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu SVACEE");
        setBackground(java.awt.Color.white);

        jLabel2.setBackground(java.awt.Color.white);
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/svacee/img/loss(1).png"))); // NOI18N

        barraFerramenta.setBackground(java.awt.Color.lightGray);
        barraFerramenta.setRollover(true);

        bDado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/svacee/img/add_page (2).png"))); // NOI18N
        bDado.setFocusable(false);
        bDado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bDado.setMaximumSize(new java.awt.Dimension(60, 45));
        bDado.setMinimumSize(new java.awt.Dimension(60, 45));
        bDado.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bDado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDadoActionPerformed(evt);
            }
        });
        barraFerramenta.add(bDado);
        barraFerramenta.add(jSeparator1);

        bTabela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/svacee/img/tabela.png"))); // NOI18N
        bTabela.setFocusable(false);
        bTabela.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bTabela.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        barraFerramenta.add(bTabela);
        barraFerramenta.add(jSeparator2);

        bGrafico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/svacee/img/chart (2).png"))); // NOI18N
        bGrafico.setFocusable(false);
        bGrafico.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bGrafico.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        barraFerramenta.add(bGrafico);
        barraFerramenta.add(jSeparator3);

        bSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/svacee/img/info (2).png"))); // NOI18N
        bSobre.setFocusable(false);
        bSobre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bSobre.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        barraFerramenta.add(bSobre);
        barraFerramenta.add(jSeparator4);

        bSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/svacee/img/sair.png"))); // NOI18N
        bSair.setFocusable(false);
        bSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bSair.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSairActionPerformed(evt);
            }
        });
        barraFerramenta.add(bSair);

        menu.setBackground(new java.awt.Color(109, 212, 247));
        menu.setForeground(new java.awt.Color(109, 212, 247));
        menu.setAlignmentX(0.55F);
        menu.setAlignmentY(0.51F);

        mArquivo.setBackground(java.awt.Color.black);
        mArquivo.setText("Arquivo");
        mArquivo.setFont(new java.awt.Font("Droid Serif", 0, 18)); // NOI18N

        smDado.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        smDado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/svacee/img/add_page (2).png"))); // NOI18N
        smDado.setText("Obter Dados CSV");
        smDado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smDadoActionPerformed(evt);
            }
        });
        mArquivo.add(smDado);

        smSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        smSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/svacee/img/sair.png"))); // NOI18N
        smSair.setText("Sair");
        smSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smSairActionPerformed(evt);
            }
        });
        mArquivo.add(smSair);

        menu.add(mArquivo);

        mVisualizar.setBackground(java.awt.Color.black);
        mVisualizar.setText("Visualizar");
        mVisualizar.setFont(new java.awt.Font("Droid Serif", 0, 18)); // NOI18N

        smTabela.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        smTabela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/svacee/img/tabela.png"))); // NOI18N
        smTabela.setText("Tabela de Dados");
        mVisualizar.add(smTabela);

        smGrafico.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        smGrafico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/svacee/img/chart (2).png"))); // NOI18N
        smGrafico.setText("Gráfico de Consumo");
        mVisualizar.add(smGrafico);

        menu.add(mVisualizar);

        mAjuda.setBackground(java.awt.Color.black);
        mAjuda.setText("Ajuda");
        mAjuda.setFont(new java.awt.Font("Droid Serif", 0, 18)); // NOI18N

        smSobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        smSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/svacee/img/info (2).png"))); // NOI18N
        smSobre.setText("Sobre");
        mAjuda.add(smSobre);

        menu.add(mAjuda);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(82, 82, 82))
            .addComponent(barraFerramenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(barraFerramenta, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(45, 45, 45))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_bSairActionPerformed

    private void smSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smSairActionPerformed
        // TODO add your handling code here:
        this.dispose();

    }//GEN-LAST:event_smSairActionPerformed

    private void bDadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDadoActionPerformed
        // TODO add your handling code here:
        lcsv.run();
    }//GEN-LAST:event_bDadoActionPerformed

    private void smDadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smDadoActionPerformed
        // TODO add your handling code here:
        lcsv.run();
    }//GEN-LAST:event_smDadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SvaceeMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SvaceeMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SvaceeMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SvaceeMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SvaceeMainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bDado;
    private javax.swing.JButton bGrafico;
    private javax.swing.JButton bSair;
    private javax.swing.JButton bSobre;
    private javax.swing.JButton bTabela;
    private javax.swing.JToolBar barraFerramenta;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JMenu mAjuda;
    private javax.swing.JMenu mArquivo;
    private javax.swing.JMenu mVisualizar;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenuItem smDado;
    private javax.swing.JMenuItem smGrafico;
    private javax.swing.JMenuItem smSair;
    private javax.swing.JMenuItem smSobre;
    private javax.swing.JMenuItem smTabela;
    // End of variables declaration//GEN-END:variables
}
